WFLY-14953 (distributable-ejb phase 1)
wildfly-clustering/wildfly pull request #8
Opened 2021-11-01 19:53 UTC by rachmatowicz

This PR holds all the work related to configuring cache factories via distributable-ejb.

2021-11-05 13:15 UTC, pferraro requested changes

2021-11-05 13:15 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/cache/distributable/DistributableCacheFactoryBuilderServiceConfigurator.java
> +        Consumer<DistributableCacheFactoryBuilder<K, V>> cacheFactoryBuilder = register(builder).provides(name);
```java
Consumer<DistributableCacheFactoryBuilder<K, V>> cacheFactoryBuilder = this.beanManagementProviderDependency.register(builder).provides(name);
```
Just inline this, so we can see what the service dependencies are.

2021-11-05 13:15 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/cache/distributable/DistributableCacheFactoryBuilderServiceConfigurator.java
> +        return this.beanManagementProviderDependency.get();
This doesn't need a separate method.

2021-11-05 13:15 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/subsystem/DistributableCacheFactoryAdd.java
> +public class DistributableCacheFactoryAdd extends AbstractAddStepHandler {
Replace these add/remove step handlers with a ResourceServiceHandler.

2021-11-05 13:15 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/subsystem/DistributableCacheFactoryRemove.java
> +public class DistributableCacheFactoryRemove extends ServiceRemoveStepHandler {
Replace with ResourceServiceHandler, see above.

2021-11-05 13:15 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/subsystem/DistributableCacheFactoryResourceDefinition.java
> +    private DistributableCacheFactoryResourceDefinition() {
Leverage ResourceDefinition logic from wildfly-clustering-common.

2021-11-05 13:15 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3RemoteServiceAdd.java
> +        final ClientMappingsRegistryProvider provider = providerFactory.createClientMappingsRegistryProvider(clientMappingsClusterName);
We only want to use the LegacyClientMappingsRegistryProviderFactory if no ClientMappingsRegistryProvider exists.

2021-11-05 13:15 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem100Parser.java
> +public class EJB3Subsystem100Parser extends EJB3Subsystem90Parser {
Doesn't it hurt inside to have to implement a parser per schema version?

2021-11-05 13:15 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/subsystem/SimpleCacheFactoryAdd.java
> +public class SimpleCacheFactoryAdd extends AbstractAddStepHandler {
Replace add/remove operations with a single ResourceServiceHandler.

2021-11-05 13:15 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/subsystem/SimpleCacheFactoryRemove.java
> +public class SimpleCacheFactoryRemove extends ServiceRemoveStepHandler {
Same as above.

2021-11-05 13:15 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/subsystem/SimpleCacheFactoryResourceDefinition.java
> +    private SimpleCacheFactoryResourceDefinition() {
Use ResourceDefinition registration logic from wildfly-clustering-common.

2021-11-09 18:57 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/deployment/README.txt
> +- dependency processors
Done.

2021-11-09 19:09 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/DistributableEjbModel.java
> +    VERSION_1_0_0(1, 0, 0), // WildFly 24
done

2021-11-09 19:10 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/DistributableEjbSchema.java
> +    VERSION_1_0(1, 0), // WildFly 24
done

2021-11-09 19:16 UTC, rachmatowicz commented on clustering/ejb/extension/pom.xml
> +        -->
Done

2021-11-09 19:29 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/ClientMappingsRegistryProviderResourceDefinition.java
> +            this.capability = new RequirementCapability(requirement);
Done

2021-11-09 19:44 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/InfinispanBeanManagementResourceDefinition.java
> +            // do we need additional requirements here?
Done.

2021-11-09 19:46 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/README.txt
> +This will allow starting a concrete bean management resource
Done

2021-11-09 20:02 UTC, rachmatowicz commented on ee-feature-pack/galleon-common/src/main/resources/feature_groups/domain-host-excludes.xml
>      </feature>
Done.

2021-11-09 20:03 UTC, rachmatowicz commented on ee-feature-pack/galleon-common/src/main/resources/feature_groups/distributable-ejb-local.xml
> +    </feature>
Included in a later commit.

2021-11-09 20:03 UTC, rachmatowicz commented on ee-feature-pack/galleon-common/src/main/resources/feature_groups/distributable-ejb.xml
> +    </feature>
Included in a later commit.

2021-11-09 20:05 UTC, rachmatowicz commented on ejb3/src/main/java/org/jboss/as/ejb3/cache/distributable/DistributableCacheFactoryBuilderServiceConfigurator.java
>          }
Done.

2021-11-10 17:44 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/DistributableEjbResourceServiceHandler.java
> +        EjbProviderRequirement.BEAN_MANAGEMENT_PROVIDER, defaultBeanManagement)
Fixed.

2021-11-10 17:44 UTC, rachmatowicz commented on ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3RemoteServiceAdd.java
> +        final ClientMappingsRegistryProvider provider = providerFactory.createClientMappingsRegistryProvider(clientMappingsClusterName);
This was fixed in a later commit.

2021-11-10 17:45 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/InfinispanBeanManagementResourceDefinition.java
> +        },
This was up for discussion (i.e. placement of the max-size attribute)

2021-11-10 17:45 UTC, rachmatowicz commented on clustering/ejb/spi/src/main/java/org/wildfly/clustering/ejb/DistributableBeanManagementProvider.java
> + * interface for obtaining BeanManagementProvider instances, used to install configured BeanManagerFactory services.
Done.

2021-11-10 17:45 UTC, rachmatowicz commented on ee-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/clustering/ejb/main/module.xml
> +        <!--WFLY-14219 Remove deprecated <module name="javax.api"/> -->
Done.

2021-11-10 17:46 UTC, rachmatowicz commented on ejb3/src/main/java/org/jboss/as/ejb3/cache/distributable/DistributableCacheFactoryBuilderServiceConfigurator.java
> +        Consumer<DistributableCacheFactoryBuilder<K, V>> cacheFactoryBuilder = register(builder).provides(name);
Done.

2021-11-10 17:46 UTC, rachmatowicz commented on ejb3/src/main/java/org/jboss/as/ejb3/cache/distributable/DistributableCacheFactoryBuilderServiceConfigurator.java
> +        return this.beanManagementProviderDependency.get();
I like to make accesssors a little more visible, but done.

2021-11-10 17:47 UTC, rachmatowicz commented on ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem100Parser.java
> +public class EJB3Subsystem100Parser extends EJB3Subsystem90Parser {
Not sure I understand this comment.

2021-11-10 17:48 UTC, rachmatowicz commented on ejb3/src/main/java/org/jboss/as/ejb3/cache/distributable/DistributableCacheFactoryBuilderServiceConfigurator.java
>      }
I used a separate method because register() was seen to be where service supplier dependencies were setup, but I have removed it.

2021-11-10 17:50 UTC, rachmatowicz commented on ejb3/src/main/java/org/jboss/as/ejb3/subsystem/DistributableCacheFactoryAdd.java
> +public class DistributableCacheFactoryAdd extends AbstractAddStepHandler {
Need to discuss this. The EJB3 subsystem doesn't generally make use of the optimizations made in the clustering subsystems with regard to registration of resources via ResourceDefinition, and i'd like to avoid living in a halfway house.

2021-12-01 21:00 UTC, closed without merging

2021-12-01 21:02 UTC, rachmatowicz commented
This PR is from an old copy of the branch and almost all of the requests for changes have been addressed. I'm closing this PR and creating  anew one with the finished branch.