Wfly 14953
wildfly-clustering/wildfly pull request #9
Opened 2021-12-01 21:13 UTC by rachmatowicz

This incorporates the "finished" changes for distributable-ejb subsystem and its integration with the ejb3 subsystem.

2021-12-02 15:19 UTC, pferraro commented
Thanks Richard. I'll rebase my branch and give it a full review on Monday.

2021-12-06 21:55 UTC, pferraro requested changes
Additionally, this needs to be rebased against master, as there are merge conflicts.

2021-12-06 21:55 UTC, pferraro commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/DistributableEjbModel.java
> +    VERSION_1_0_0(1, 0, 0), // WildFly 26
You'll want to update this comment, as we've missed the window for WF26.

2021-12-06 21:55 UTC, pferraro commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/DistributableEjbSchema.java
> +    VERSION_1_0(1, 0), // WildFly 26
You'll want to update this comment, as we've missed the window for WF26.

2021-12-06 21:55 UTC, pferraro commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/InfinispanBeanManagementResourceDefinition.java
> +            // do we need additional requirements here?
This capability requires ClientMappingsRegistryProviderResourceDefinition.Capability.CLIENT_MAPPINGS_REGISTRY_PROVIDER.getName()

2021-12-06 21:55 UTC, pferraro commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/InfinispanBeanManagementResourceDefinition.java
> +                        // default value?
No default value.  When undefined, we never evict entries.

2021-12-06 21:55 UTC, pferraro commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/InfinispanBeanManagementResourceDefinition.java
> +                return builder.setAllowExpression(false)
This attribute should allow expressions.

2021-12-06 21:55 UTC, pferraro commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/InfinispanBeanManagementServiceConfigurator.java
> +     */
Missing @Override annotation, which would make this comment redundant.

2021-12-06 21:55 UTC, pferraro commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/InfinispanBeanManagementServiceConfigurator.java
> +    public String getCacheName() {
Missing @Override annotation.

2021-12-06 21:55 UTC, pferraro commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/InfinispanBeanManagementServiceConfigurator.java
> +    public int getMaxSize() {
Missing @Override annotation.

2021-12-06 21:55 UTC, pferraro commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/InfinispanClientMappingsRegistryProviderResourceDefinition.java
> +    public InfinispanClientMappingsRegistryProviderResourceDefinition() {
Use package protected visibility.

2021-12-06 21:55 UTC, pferraro commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/ClientMappingsRegistryProviderResourceDefinition.java
> +    public ClientMappingsRegistryProviderResourceDefinition(PathElement path, UnaryOperator<ResourceDescriptor> configurator, ResourceServiceConfiguratorFactory serviceConfiguratorFactory) {
Use package protected visibility.

2021-12-06 21:55 UTC, pferraro commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/LocalClientMappingsRegistryProviderResourceDefinition.java
> +    public LocalClientMappingsRegistryProviderResourceDefinition() {
Use package protected visibility.

2021-12-06 21:55 UTC, pferraro commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/LocalClientMappingsRegistryProviderServiceConfigurator.java
> +        // return new LocalClientMappingsRegistryProvider();
I would note that the string values used here are effectively arbitrary.

2021-12-06 21:55 UTC, pferraro commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/InfinispanClientMappingsRegistryProviderServiceConfigurator.java
> +        this.cacheName = CACHE.resolveModelAttribute(context, model).asString();
Use ModelNode.asStringOrNull() instead of asString() to handle undefined values.

2021-12-06 21:55 UTC, pferraro commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/InfinispanClientMappingsRegistryProviderServiceConfigurator.java
> +        return super.configure(context, model);
return this;

The super implementation is a no-op.

2021-12-07 14:18 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/DistributableEjbModel.java
> +    VERSION_1_0_0(1, 0, 0), // WildFly 26
Done

2021-12-07 14:18 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/DistributableEjbSchema.java
> +    VERSION_1_0(1, 0), // WildFly 26
Done

2021-12-07 14:18 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/InfinispanBeanManagementResourceDefinition.java
> +            // do we need additional requirements here?
Done

2021-12-07 14:19 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/InfinispanBeanManagementResourceDefinition.java
> +                        // default value?
Done

2021-12-07 14:19 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/InfinispanBeanManagementResourceDefinition.java
> +                return builder.setAllowExpression(false)
Done

2021-12-07 14:20 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/LocalClientMappingsRegistryProviderServiceConfigurator.java
> +        // return new LocalClientMappingsRegistryProvider();
Not sure what you mean here...

2021-12-07 14:20 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/ClientMappingsRegistryProviderResourceDefinition.java
> +    public ClientMappingsRegistryProviderResourceDefinition(PathElement path, UnaryOperator<ResourceDescriptor> configurator, ResourceServiceConfiguratorFactory serviceConfiguratorFactory) {
You mean on the currently private variables, right?

2021-12-07 14:20 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/InfinispanClientMappingsRegistryProviderServiceConfigurator.java
> +        this.cacheName = CACHE.resolveModelAttribute(context, model).asString();
Done.

2021-12-07 14:20 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/InfinispanClientMappingsRegistryProviderServiceConfigurator.java
> +        return super.configure(context, model);
Done

2021-12-07 14:24 UTC, pferraro commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/LocalClientMappingsRegistryProviderServiceConfigurator.java
> +        // return new LocalClientMappingsRegistryProvider();
Meaning, the values "ejb" and "client-mappings" are not constrained by any resources.

2021-12-07 14:32 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/LocalClientMappingsRegistryProviderServiceConfigurator.java
> +        // return new LocalClientMappingsRegistryProvider();
Done

2021-12-07 14:32 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/LocalClientMappingsRegistryProviderResourceDefinition.java
> +    public LocalClientMappingsRegistryProviderResourceDefinition() {
Done

2021-12-07 14:32 UTC, rachmatowicz commented on clustering/ejb/extension/src/main/java/org/wildfly/extension/clustering/ejb/ClientMappingsRegistryProviderResourceDefinition.java
> +    public ClientMappingsRegistryProviderResourceDefinition(PathElement path, UnaryOperator<ResourceDescriptor> configurator, ResourceServiceConfiguratorFactory serviceConfiguratorFactory) {
Done

2021-12-07 14:33 UTC, rachmatowicz commented
The changes have been made, running the tests again before pushing the corrected rebased branch.

2021-12-07 15:55 UTC, merged

2021-12-08 00:18 UTC, rachmatowicz commented
Hallelujah.